version: 1.0
appName: SERVICE_MASTER
services:
  servicePost:
    endpoints:
      getAllPosts:
        path: /posts
        method: GET
      getPostsById:
        path: /posts/[id]
        method: GET
      createPost:
        path: /posts
        method: POST
    config:
      origin: https://jsonplaceholder.typicode.com/
      enableAuth: false
  serviceUser:
    endpoints:
      getAllUsers:
        path: /users
        method: GET
      getUserById:
        path: /users/[id]
        method: GET
    config:
      origin: https://jsonplaceholder.typicode.com/
      enableAuth: false
  serviceCep:
    endpoints:
      getAddressByCep:
        path: /ws/[cep]/[type]
        method: GET
    config:
      origin: https://viacep.com.br/
      enableAuth: false
authInfo:
  origin: http://origin.s3.24552235235
  enpoint: /api/auth
  secret: b80026d579eb33a70fe44adc7a9a3950dcaa6b6dccf6e93bc0be2d7608ac0ed5
config:
  useCache: false
  cache:
    periodic: 1
  useRateLimit: false
  rateLimit:
    permitLimit: 10
    windowTypeTime: HOURS
    windowTime: 2
    queueProcessingOrder: OLDEST_FIRST
    queueLimit: 0