version: 1.0
appName: SERVICE_MASTER
services:
  serviceUser:
    version: 1
    endpoints:
      getUsers:
        origin: /api/user/get-users
        method: GET
      createUser:
        origin: /api/user/create-user
        method: POST
      deleteUser:
        origin: /api/user/delete-user
        method: DELETE
    config:
      origin: http://amazon.s3.78745ghjhgts.xyz67834
      enableAuth: false
  serviceEmail:
    version: 2
    endpoints:
      sendEmail:
        origin: /api/email/send-email-service
        method: POST
      receiveEmail:
        origin: /api/email/receive-email
        method: GET
    config:
      origin: http://amazon.s3.78745ghjhgts.xyz
      enableAuth: true
authInfo:
  enpoint: /api/auth
  secret: b80026d579eb33a70fe44adc7a9a3950dcaa6b6dccf6e93bc0be2d7608ac0ed5
config:
  useCache: false
  cache:
    periodic: 1
  useRateLimit: true
  rateLimit:
    permitLimit: 10
    windowTypeTime: HOURS
    windowTime: 2
    queueProcessingOrder: OLDEST_FIRST
    queueLimit: 0