version: 1.0
appName: SERVICE_MASTER
services:
  servicePost:
    endpoints:
      getAllPosts:
        path: /posts
        method: GET
      getPostsById:
        path: /posts/[id]
        method: GET
      createPost:
        path: /posts
        method: POST
    config:
      origin: https://jsonplaceholder.typicode.com/
  serviceUser:
    endpoints:
      getAllUsers:
        path: /users
        method: GET
      getUserById:
        path: /users/[id]
        method: GET
      postUser:
        path: /users
        method: POST
    config:
      origin: http://localhost:3000
  serviceCep:
    endpoints:
      getAddressByCep:
        path: /ws/[cep]/[type]
        method: GET
    config:
      origin: https://viacep.com.br/
config:
  accessToken: 123456
  auth:
    origin: http://localhost:3000
    path: /verify-user
  useCache: false
  cache:
    periodic: 1
  useRateLimit: false
  rateLimit:
    permitLimit: 10
    windowTypeTime: HOURS
    windowTime: 2
    queueProcessingOrder: OLDEST_FIRST
    queueLimit: 0
  httpRetry:
    delayTime: 5
    delayTypeTime: SECONDS
    maxRetryAttempts: 6